### ISSUE TITLE
Block-options can cover block-dropdowns and make them hard to use

### ISSUE THREAD

**Issue by peterstollenwerk** [youngcut/kirby-grid-block#3]
Is it possible to show the option-menu only for one, the active block inside the grid-block? 

Screenshot:
<img width="831" alt="Bildschirmfoto 2021-12-20 um 15 05 52" src="https://user-images.githubusercontent.com/11475106/146779888-a5921713-7811-43ee-917f-2cb706534d37.png">

**Comment by youngcut** [comment]
That could certainly be done somehow. Or at least that the dropdown is at the front.
I can take a look at it in January. If it's urgent, I would be happy for a pull request

**Comment by peterstollenwerk** [comment]
Hi youngcut, it´s not urgent for now. If you find the time, let me know. Otherwise I´ll give it a shot, as soon as more important stuff is out of the way.
